### ISSUE TITLE
Ongoing events?

### ISSUE THREAD

**Issue by saltybeagle** [unl/UNL_UCBCN_Frontend#11]
Where are the ongoing events? These only show up on the Day view, but should be present when the day-view is shown.

**Comment by mfairchild365** [comment]
@saltybeagle Can you elaborate on this?  Did you mean: "These only show up on the Day view, but should be present when the **month**-view is shown."

Also, in the live system ongoing events are in a separate list within the day view.  Currently in the new system they are combined into a single list.  Was this the intention, or did you want them separate?

**Comment by saltybeagle** [comment]
It might make sense that they're contained in the same list, they just need to be displayed differently.
