### ISSUE TITLE
Ensure year view is working

### ISSUE THREAD

**Issue by saltybeagle** [unl/UNL_UCBCN_Frontend#13]
The year view needs to render 12 "month widgets" for the current year.

**Comment by kabel** [comment]
This view does not currently, properly handle the ICS or RSS formats. Should something be done to prevent these invalid formats from rendering?

**Comment by mfairchild365** [comment]
I don't think these views should handle ICS or RSS formats, at least for this sprint.  They were never implemented in the old front end, and they could be very intensive on the server.
