### ISSUE TITLE
Ensure ICS format is working

### ISSUE THREAD

**Issue by mfairchild365** [unl/UNL_UCBCN_Frontend#37]

**Comment by kabel** [comment]
Does the commit in master ahead of this branch need to be integrated?

**Comment by mfairchild365** [comment]
Assuming you are talking about this one: https://github.com/unl/UNL_UCBCN_Frontend/blob/0817f01f70b8d36c4ce654fe9b062102b51c24d7/www/templates/default/EventInstance_icalendar.tpl.php

It appears to be included in this branch already.
