### ISSUE TITLE
Day header should be stuck to the top of the events list

### ISSUE THREAD

**Issue by mfairchild365** [unl/UNL_UCBCN_Frontend#50]
Desktop: It should also change as you scroll to match the date of the current (top most visible) event.

Mobile: It should not sticky, and a new day header should be inserted before the first event for each day

**Comment by kabel** [comment]
I implemented this with a jQuery plugin called sticky-kit. At the moment, I'm not incredibly confident in how it responds to page resizes (responsive). Perhaps we should revisit this with a different plugin and see if we have better results.

**Comment by mfairchild365** [comment]
As discussed yesterday, we feel confident that this will work for now.  If we experience problems, we can revisit later.
