### ISSUE TITLE
Event calendar UI shows events on day, but no events exist

### ISSUE THREAD

**Issue by smeranda** [unl/UNL_UCBCN_Frontend#6]
The calendar widget on the left seems to indicate events exist on a day with the blue shading, however it's a lie!
![Screen Shot 2013-03-10 at 3 03 20 PM](https://f.cloud.github.com/assets/302114/241588/b364b2dc-89bd-11e2-9968-e610ce51b91f.png)

**Comment by saltybeagle** [comment]
When the month widget grabs the dates with recurring events, the current calendar is not considered. The RecurringDate::getRecurringDates($month) method should accept an optional calendar_id parameter.
