### ISSUE TITLE
Need style for "Today" of MonthWidget

### ISSUE THREAD

**Issue by kabel** [unl/UNL_UCBCN_Frontend#63]

**Comment by skoolbus39** [comment]
![screen shot 2014-07-20 at 4 33 00 pm](https://cloud.githubusercontent.com/assets/5385125/3638608/c146160a-1055-11e4-80df-0935d7b3029b.png)

The red solid square indicates "today."
The gray solid square indicates the day currently being viewed. The gray color ties it to the calendar header above it, as well as the day header in the right hand column.  
The red outline is the hover state for days that aren't "today" or the day currently being viewed.
This styling is also consistent with the pagination styling used in the WDN 4.0 template:  http://www.unl.edu/wdn/templates_4.0/examples/#pagination.html.

**Comment by skoolbus39** [comment]
Also of note: the mockup was designed before we updated the colors. They will need to be updated to the nearest color in the new 4.0 palette. I'm willing to make these adjustments if necessary.

**Comment by skoolbus39** [comment]
To clarify any potential confusion: the day header on the right should probably read "Wednesday, Feb. 5, 2014."
