### ISSUE TITLE
Image view is missing

### ISSUE THREAD

**Issue by mfairchild365** [unl/UNL_UCBCN_Frontend#67]
In the XML (#65) output, it lists a URL for images.  The image URL is formatted like this:

```
events.unl.edu/?image&id=72316
```

where ID is the event ID.

This view is currently missing and needs to be added.

**Comment by kabel** [comment]
The Image class has not been updated to provide a RESTful URL. The planned route is `images/####`

Perhaps we need to keep with legacy route like we do for the monthwidget?

**Comment by mfairchild365** [comment]
Both the legacy route and new route have been implemented.
