### ISSUE TITLE
JSON output is broken

### ISSUE THREAD

**Issue by mfairchild365** [unl/UNL_UCBCN_Frontend#76]
It looks like we are missing a library to convert xml to JSON, which is what the JSON output was doing.

**Comment by kabel** [comment]
I would _not_ recommend using this library again. `json_encode` should be the preferred method. Following similar templates as the XML format.

**Comment by mfairchild365** [comment]
Can you elaborate on what the problem with using the library is?

From what I can tell, the idea behind using the library was to make the data available via JSON without needless code duplication.  If the JSON output needed extra or different information than the xml, implementing similar templates would make sense.

I'm not necessarily opposed to moving to json templates, but I am concerned about breaking anything that uses the current JSON output (and I'm not sure anything does at the moment) and code duplication.

**Comment by kabel** [comment]
I'm against the added complexity of having to both generate _and_ parse the XML format just to build a JSON representation. Ideally, these formats would share some sort of model logic that generated data in a way that would make outputting in either format quick.

**Comment by saltybeagle** [comment]
I agree with @kabel. The output formats should support the clients that read and interpret that format.

The XML format was intended to follow the Berkeley schema. The JSON output should be formatted in a way to support clients that can consume JSON.

You're correct, @mfairchild365, adding a proper JSON output format will take some additional work. But, if there is no difference in the structure between the JSON and XML, clients could use the XML and use their own libraries to convert it to JSON.
