### ISSUE TITLE
Force title case for event location names

### ISSUE THREAD

**Issue by mfairchild365** [unl/UNL_UCBCN_Frontend#86]

**Comment by mfairchild365** [comment]
I re-oped this issue because we did not consider the possibility of acronyms.  The system currently contains numerous location names that are either acronyms or contain acronyms.

The better thing to do is to not transform the location names in the code, and to edit the location names in the database.

Thoughts?  @kabel @skoolbus39

**Comment by kabel** [comment]
Agreed.

**Comment by mfairchild365** [comment]
Fixed in https://github.com/unl/UNL_UCBCN_Frontend/pull/137
