### ISSUE TITLE
Invalid output in ical format

### ISSUE THREAD

**Issue by mfairchild365** [unl/UNL_UCBCN_Frontend#90]
for example: www/2014/08/20/90431/?format=ical

Events with invalid code points in the description:

| datetime | event |
| --- | --- |
| 90431 | 77412 |
| 89582 | 76615 |
| 88626 | 75756 |
| 88252 | 75422 |
| 89587 | 76620 |

**Comment by kabel** [comment]
I believe we have determined this to be a fault in the Controller template that is wrapping (inserting `\r\n`)lines at 75 bytes, which leads to situations that break multibyte characters.

**Comment by kabel** [comment]
This sort of "problem" is documented in http://tools.ietf.org/html/rfc5545. Clients are supposed to be able to "unfold" the line properly, but implementing better multibyte folding couldn't hurt.

**Comment by mfairchild365** [comment]
good find kabel.  I know that this is an existing problem in some systems (the nebraska app), so I think we should implement better multibyte folding.
